# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vexp.ui'
#
# Created: Wed Jan 25 15:57:06 2012
#      by: pyside-uic 0.2.11 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("nyancat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.qvtkWidget = QVTKWidget(self.verticalLayoutWidget)
        self.qvtkWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.qvtkWidget.setObjectName("qvtkWidget")
        self.horizontalLayout_5.addWidget(self.qvtkWidget)
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ibox = QtGui.QTextBrowser(self.horizontalLayoutWidget)
        self.ibox.setMinimumSize(QtCore.QSize(0, 100))
        self.ibox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ibox.setObjectName("ibox")
        self.horizontalLayout_4.addWidget(self.ibox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bPlotK = QtGui.QRadioButton(self.frame_2)
        self.bPlotK.setChecked(True)
        self.bPlotK.setObjectName("bPlotK")
        self.verticalLayout_2.addWidget(self.bPlotK)
        self.bPlotdK = QtGui.QRadioButton(self.frame_2)
        self.bPlotdK.setObjectName("bPlotdK")
        self.verticalLayout_2.addWidget(self.bPlotdK)
        self.bPlotKFFT = QtGui.QRadioButton(self.frame_2)
        self.bPlotKFFT.setObjectName("bPlotKFFT")
        self.verticalLayout_2.addWidget(self.bPlotKFFT)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.resetButton = QtGui.QPushButton(self.frame)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_6.addWidget(self.resetButton)
        self.prevButton = QtGui.QPushButton(self.frame)
        self.prevButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_6.addWidget(self.prevButton)
        self.nextButton = QtGui.QPushButton(self.frame)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_6.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.fitButton = QtGui.QPushButton(self.frame)
        self.fitButton.setObjectName("fitButton")
        self.verticalLayout.addWidget(self.fitButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_OpenGeometry = QtGui.QAction(MainWindow)
        self.action_OpenGeometry.setObjectName("action_OpenGeometry")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_OpenGeometry)
        self.menuFile.addAction(self.action_Close)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Vortex Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.bPlotK.setText(QtGui.QApplication.translate("MainWindow", "Curvature Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.bPlotdK.setText(QtGui.QApplication.translate("MainWindow", "dCurvature Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.bPlotKFFT.setText(QtGui.QApplication.translate("MainWindow", "Curvature FFT Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("MainWindow", "&Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "&Next", None, QtGui.QApplication.UnicodeUTF8))
        self.fitButton.setText(QtGui.QApplication.translate("MainWindow", "Fit Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_OpenGeometry.setText(QtGui.QApplication.translate("MainWindow", "Open &Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))

from QVTKWidget import QVTKWidget
