/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vpg_NativeCode */

#ifndef _Included_com_intel_vpg_NativeCode
#define _Included_com_intel_vpg_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    detectFaces
 * Signature: (Lcom/intel/vpg/IntImage;I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_intel_vpg_NativeCode_detectFaces
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    prepareTracking
 * Signature: (Lcom/intel/vpg/IntImage;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_intel_vpg_NativeCode_prepareTracking
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    track2
 * Signature: (Lcom/intel/vpg/IntImage;Lcom/intel/vpg/IntImage;[DLcom/intel/vpg/MotionParameter;)Lcom/intel/vpg/MotionParameter;
 */
JNIEXPORT jobject JNICALL Java_com_intel_vpg_NativeCode_track2
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jobject);

/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    track1
 * Signature: (Lcom/intel/vpg/IntImage;Lcom/intel/vpg/IntImage;Lcom/intel/vpg/MotionParameter;)Lcom/intel/vpg/MotionParameter;
 */
JNIEXPORT jobject JNICALL Java_com_intel_vpg_NativeCode_track1
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    resampleRegion
 * Signature: (Lcom/intel/vpg/IntImage;Lcom/intel/vpg/IntImage;Lcom/intel/vpg/MotionParameter;)Lcom/intel/vpg/IntImage;
 */
JNIEXPORT jobject JNICALL Java_com_intel_vpg_NativeCode_resampleRegion
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_intel_vpg_NativeCode
 * Method:    resize
 * Signature: ([III[III)V
 */
JNIEXPORT void JNICALL Java_com_intel_vpg_NativeCode_resize
  (JNIEnv *, jclass, jintArray, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
